// Generated by gencpp from file motor/skate_command.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_SKATE_COMMAND_H
#define MOTOR_MESSAGE_SKATE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motor
{
template <class ContainerAllocator>
struct skate_command_
{
  typedef skate_command_<ContainerAllocator> Type;

  skate_command_()
    : header()
    , calibration_enable(0)
    , command_target(0)  {
    }
  skate_command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , calibration_enable(0)
    , command_target(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _calibration_enable_type;
  _calibration_enable_type calibration_enable;

   typedef int32_t _command_target_type;
  _command_target_type command_target;




  typedef boost::shared_ptr< ::motor::skate_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor::skate_command_<ContainerAllocator> const> ConstPtr;

}; // struct skate_command_

typedef ::motor::skate_command_<std::allocator<void> > skate_command;

typedef boost::shared_ptr< ::motor::skate_command > skate_commandPtr;
typedef boost::shared_ptr< ::motor::skate_command const> skate_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor::skate_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor::skate_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motor': ['/home/saurabh/catkin_ws/src/motor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor::skate_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::skate_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::skate_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::skate_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::skate_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::skate_command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor::skate_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb77e7d8ddea947728653dde426e34c7";
  }

  static const char* value(const ::motor::skate_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb77e7d8ddea9477ULL;
  static const uint64_t static_value2 = 0x28653dde426e34c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor::skate_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor/skate_command";
  }

  static const char* value(const ::motor::skate_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor::skate_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 calibration_enable\n\
int32 command_target\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::motor::skate_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor::skate_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.calibration_enable);
      stream.next(m.command_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct skate_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor::skate_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor::skate_command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "calibration_enable: ";
    Printer<int32_t>::stream(s, indent + "  ", v.calibration_enable);
    s << indent << "command_target: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MESSAGE_SKATE_COMMAND_H
