// Generated by gencpp from file motor/zero_point.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_ZERO_POINT_H
#define MOTOR_MESSAGE_ZERO_POINT_H

#include <ros/service_traits.h>


#include <motor/zero_pointRequest.h>
#include <motor/zero_pointResponse.h>


namespace motor
{

struct zero_point
{

typedef zero_pointRequest Request;
typedef zero_pointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct zero_point
} // namespace motor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor::zero_point > {
  static const char* value()
  {
    return "c332db600bdaaaed12be73a022ed8ae1";
  }

  static const char* value(const ::motor::zero_point&) { return value(); }
};

template<>
struct DataType< ::motor::zero_point > {
  static const char* value()
  {
    return "motor/zero_point";
  }

  static const char* value(const ::motor::zero_point&) { return value(); }
};


// service_traits::MD5Sum< ::motor::zero_pointRequest> should match 
// service_traits::MD5Sum< ::motor::zero_point > 
template<>
struct MD5Sum< ::motor::zero_pointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor::zero_point >::value();
  }
  static const char* value(const ::motor::zero_pointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor::zero_pointRequest> should match 
// service_traits::DataType< ::motor::zero_point > 
template<>
struct DataType< ::motor::zero_pointRequest>
{
  static const char* value()
  {
    return DataType< ::motor::zero_point >::value();
  }
  static const char* value(const ::motor::zero_pointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor::zero_pointResponse> should match 
// service_traits::MD5Sum< ::motor::zero_point > 
template<>
struct MD5Sum< ::motor::zero_pointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor::zero_point >::value();
  }
  static const char* value(const ::motor::zero_pointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor::zero_pointResponse> should match 
// service_traits::DataType< ::motor::zero_point > 
template<>
struct DataType< ::motor::zero_pointResponse>
{
  static const char* value()
  {
    return DataType< ::motor::zero_point >::value();
  }
  static const char* value(const ::motor::zero_pointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_MESSAGE_ZERO_POINT_H
