// Generated by gencpp from file motor/Num.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_NUM_H
#define MOTOR_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motor
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : header()
    , f1(0)
    , f2(0)
    , f3(0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)
    , ax(0.0)
    , ay(0.0)
    , az(0.0)
    , rp(0.0)
    , ry(0.0)
    , rr(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , f1(0)
    , f2(0)
    , f3(0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)
    , ax(0.0)
    , ay(0.0)
    , az(0.0)
    , rp(0.0)
    , ry(0.0)
    , rr(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _f1_type;
  _f1_type f1;

   typedef int32_t _f2_type;
  _f2_type f2;

   typedef int32_t _f3_type;
  _f3_type f3;

   typedef double _qx_type;
  _qx_type qx;

   typedef double _qy_type;
  _qy_type qy;

   typedef double _qz_type;
  _qz_type qz;

   typedef double _qw_type;
  _qw_type qw;

   typedef double _ax_type;
  _ax_type ax;

   typedef double _ay_type;
  _ay_type ay;

   typedef double _az_type;
  _az_type az;

   typedef double _rp_type;
  _rp_type rp;

   typedef double _ry_type;
  _ry_type ry;

   typedef double _rr_type;
  _rr_type rr;




  typedef boost::shared_ptr< ::motor::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::motor::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::motor::Num > NumPtr;
typedef boost::shared_ptr< ::motor::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motor': ['/home/saurabh/catkin_ws/src/motor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::Num_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c819e3d7118a7e8382129f8ffeccd87";
  }

  static const char* value(const ::motor::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c819e3d7118a7e8ULL;
  static const uint64_t static_value2 = 0x382129f8ffeccd87ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor/Num";
  }

  static const char* value(const ::motor::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 f1\n\
int32 f2\n\
int32 f3\n\
float64 qx\n\
float64 qy\n\
float64 qz\n\
float64 qw\n\
float64 ax\n\
float64 ay\n\
float64 az\n\
float64 rp\n\
float64 ry\n\
float64 rr\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::motor::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.f1);
      stream.next(m.f2);
      stream.next(m.f3);
      stream.next(m.qx);
      stream.next(m.qy);
      stream.next(m.qz);
      stream.next(m.qw);
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.az);
      stream.next(m.rp);
      stream.next(m.ry);
      stream.next(m.rr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor::Num_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "f1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.f1);
    s << indent << "f2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.f2);
    s << indent << "f3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.f3);
    s << indent << "qx: ";
    Printer<double>::stream(s, indent + "  ", v.qx);
    s << indent << "qy: ";
    Printer<double>::stream(s, indent + "  ", v.qy);
    s << indent << "qz: ";
    Printer<double>::stream(s, indent + "  ", v.qz);
    s << indent << "qw: ";
    Printer<double>::stream(s, indent + "  ", v.qw);
    s << indent << "ax: ";
    Printer<double>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<double>::stream(s, indent + "  ", v.ay);
    s << indent << "az: ";
    Printer<double>::stream(s, indent + "  ", v.az);
    s << indent << "rp: ";
    Printer<double>::stream(s, indent + "  ", v.rp);
    s << indent << "ry: ";
    Printer<double>::stream(s, indent + "  ", v.ry);
    s << indent << "rr: ";
    Printer<double>::stream(s, indent + "  ", v.rr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MESSAGE_NUM_H
