// Generated by gencpp from file motor/states.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_STATES_H
#define MOTOR_MESSAGE_STATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motor
{
template <class ContainerAllocator>
struct states_
{
  typedef states_<ContainerAllocator> Type;

  states_()
    : header()
    , state(0)
    , set_point(0)  {
    }
  states_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , set_point(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _state_type;
  _state_type state;

   typedef int32_t _set_point_type;
  _set_point_type set_point;




  typedef boost::shared_ptr< ::motor::states_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor::states_<ContainerAllocator> const> ConstPtr;

}; // struct states_

typedef ::motor::states_<std::allocator<void> > states;

typedef boost::shared_ptr< ::motor::states > statesPtr;
typedef boost::shared_ptr< ::motor::states const> statesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor::states_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor::states_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motor': ['/home/saurabh/catkin_ws/src/motor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor::states_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::states_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::states_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::states_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::states_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::states_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor::states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c54f357503453db8f84f3b13454e6f8";
  }

  static const char* value(const ::motor::states_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c54f357503453dbULL;
  static const uint64_t static_value2 = 0x8f84f3b13454e6f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor::states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor/states";
  }

  static const char* value(const ::motor::states_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor::states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 state\n\
int32 set_point\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::motor::states_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor::states_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.set_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct states_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor::states_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor::states_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "set_point: ";
    Printer<int32_t>::stream(s, indent + "  ", v.set_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MESSAGE_STATES_H
