// Generated by gencpp from file motor/yaml_values.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_YAML_VALUES_H
#define MOTOR_MESSAGE_YAML_VALUES_H

#include <ros/service_traits.h>


#include <motor/yaml_valuesRequest.h>
#include <motor/yaml_valuesResponse.h>


namespace motor
{

struct yaml_values
{

typedef yaml_valuesRequest Request;
typedef yaml_valuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yaml_values
} // namespace motor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor::yaml_values > {
  static const char* value()
  {
    return "b0738748015b35d4efcebe36d64e715c";
  }

  static const char* value(const ::motor::yaml_values&) { return value(); }
};

template<>
struct DataType< ::motor::yaml_values > {
  static const char* value()
  {
    return "motor/yaml_values";
  }

  static const char* value(const ::motor::yaml_values&) { return value(); }
};


// service_traits::MD5Sum< ::motor::yaml_valuesRequest> should match 
// service_traits::MD5Sum< ::motor::yaml_values > 
template<>
struct MD5Sum< ::motor::yaml_valuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor::yaml_values >::value();
  }
  static const char* value(const ::motor::yaml_valuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor::yaml_valuesRequest> should match 
// service_traits::DataType< ::motor::yaml_values > 
template<>
struct DataType< ::motor::yaml_valuesRequest>
{
  static const char* value()
  {
    return DataType< ::motor::yaml_values >::value();
  }
  static const char* value(const ::motor::yaml_valuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor::yaml_valuesResponse> should match 
// service_traits::MD5Sum< ::motor::yaml_values > 
template<>
struct MD5Sum< ::motor::yaml_valuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor::yaml_values >::value();
  }
  static const char* value(const ::motor::yaml_valuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor::yaml_valuesResponse> should match 
// service_traits::DataType< ::motor::yaml_values > 
template<>
struct DataType< ::motor::yaml_valuesResponse>
{
  static const char* value()
  {
    return DataType< ::motor::yaml_values >::value();
  }
  static const char* value(const ::motor::yaml_valuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_MESSAGE_YAML_VALUES_H
