// Generated by gencpp from file motor/zero_pointRequest.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_ZERO_POINTREQUEST_H
#define MOTOR_MESSAGE_ZERO_POINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor
{
template <class ContainerAllocator>
struct zero_pointRequest_
{
  typedef zero_pointRequest_<ContainerAllocator> Type;

  zero_pointRequest_()
    : num(false)  {
    }
  zero_pointRequest_(const ContainerAllocator& _alloc)
    : num(false)  {
  (void)_alloc;
    }



   typedef uint8_t _num_type;
  _num_type num;




  typedef boost::shared_ptr< ::motor::zero_pointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor::zero_pointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct zero_pointRequest_

typedef ::motor::zero_pointRequest_<std::allocator<void> > zero_pointRequest;

typedef boost::shared_ptr< ::motor::zero_pointRequest > zero_pointRequestPtr;
typedef boost::shared_ptr< ::motor::zero_pointRequest const> zero_pointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor::zero_pointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor::zero_pointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motor': ['/home/saurabh/catkin_ws/src/motor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor::zero_pointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::zero_pointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::zero_pointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::zero_pointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::zero_pointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::zero_pointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor::zero_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c4b983bdbcc51dc7ef8a75dea21c0f0";
  }

  static const char* value(const ::motor::zero_pointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c4b983bdbcc51dcULL;
  static const uint64_t static_value2 = 0x7ef8a75dea21c0f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor::zero_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor/zero_pointRequest";
  }

  static const char* value(const ::motor::zero_pointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor::zero_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool num\n\
";
  }

  static const char* value(const ::motor::zero_pointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor::zero_pointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct zero_pointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor::zero_pointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor::zero_pointRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MESSAGE_ZERO_POINTREQUEST_H
