(cl:in-package motor-msg)
(cl:export '(HEADER-VAL
          HEADER
          F1-VAL
          F1
          F2-VAL
          F2
          F3-VAL
          F3
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          QW-VAL
          QW
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          RP-VAL
          RP
          RY-VAL
          RY
          RR-VAL
          RR
))