(cl:in-package motor-msg)
(cl:export '(HEADER-VAL
          HEADER
          FORCE_FRONT_OUTER-VAL
          FORCE_FRONT_OUTER
          FORCE_FRONT_INNER-VAL
          FORCE_FRONT_INNER
          FORCE_REAR-VAL
          FORCE_REAR
          IMU_QUAT_X-VAL
          IMU_QUAT_X
          IMU_QUAT_Y-VAL
          IMU_QUAT_Y
          IMU_QUAT_Z-VAL
          IMU_QUAT_Z
          IMU_QUAT_W-VAL
          IMU_QUAT_W
          IMU_ACCEL_X-VAL
          IMU_ACCEL_X
          IMU_ACCEL_Y-VAL
          IMU_ACCEL_Y
          IMU_ACCEL_Z-VAL
          IMU_ACCEL_Z
          IMU_RATE_X-VAL
          IMU_RATE_X
          IMU_RATE_Y-VAL
          IMU_RATE_Y
          IMU_RATE_Z-VAL
          IMU_RATE_Z
          VELOCITY_CMD_REAR-VAL
          VELOCITY_CMD_REAR
          VELOCITY_CMD_FRONT-VAL
          VELOCITY_CMD_FRONT
          SKATE_FAULT-VAL
          SKATE_FAULT
          POSITION_FILT_REAR-VAL
          POSITION_FILT_REAR
          POSITION_FILT_FRONT-VAL
          POSITION_FILT_FRONT
          VELOCITY_FILT_REAR-VAL
          VELOCITY_FILT_REAR
          VELOCITY_FILT_FRONT-VAL
          VELOCITY_FILT_FRONT
          DEAD_MAN_ENABLE-VAL
          DEAD_MAN_ENABLE
          CONTROLLER_TARGET-VAL
          CONTROLLER_TARGET
          SKATE_MODE-VAL
          SKATE_MODE
))