# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motor/yaml_valuesRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class yaml_valuesRequest(genpy.Message):
  _md5sum = "3c4b983bdbcc51dc7ef8a75dea21c0f0"
  _type = "motor/yaml_valuesRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool num
"""
  __slots__ = ['num']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       num

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(yaml_valuesRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.num is None:
        self.num = False
    else:
      self.num = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.num,) = _struct_B.unpack(str[start:end])
      self.num = bool(self.num)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.num,) = _struct_B.unpack(str[start:end])
      self.num = bool(self.num)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motor/yaml_valuesResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class yaml_valuesResponse(genpy.Message):
  _md5sum = "599f443ae0f39cd3fc016639ad207690"
  _type = "motor/yaml_valuesResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 left_bias_f1
float64 left_bias_f2
float64 left_bias_f3
float64 left_gain_f1
float64 left_gain_f2
float64 left_gain_f3
float64 right_bias_f1
float64 right_bias_f2
float64 right_bias_f3
float64 right_gain_f1
float64 right_gain_f2
float64 right_gain_f3

"""
  __slots__ = ['left_bias_f1','left_bias_f2','left_bias_f3','left_gain_f1','left_gain_f2','left_gain_f3','right_bias_f1','right_bias_f2','right_bias_f3','right_gain_f1','right_gain_f2','right_gain_f3']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_bias_f1,left_bias_f2,left_bias_f3,left_gain_f1,left_gain_f2,left_gain_f3,right_bias_f1,right_bias_f2,right_bias_f3,right_gain_f1,right_gain_f2,right_gain_f3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(yaml_valuesResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_bias_f1 is None:
        self.left_bias_f1 = 0.
      if self.left_bias_f2 is None:
        self.left_bias_f2 = 0.
      if self.left_bias_f3 is None:
        self.left_bias_f3 = 0.
      if self.left_gain_f1 is None:
        self.left_gain_f1 = 0.
      if self.left_gain_f2 is None:
        self.left_gain_f2 = 0.
      if self.left_gain_f3 is None:
        self.left_gain_f3 = 0.
      if self.right_bias_f1 is None:
        self.right_bias_f1 = 0.
      if self.right_bias_f2 is None:
        self.right_bias_f2 = 0.
      if self.right_bias_f3 is None:
        self.right_bias_f3 = 0.
      if self.right_gain_f1 is None:
        self.right_gain_f1 = 0.
      if self.right_gain_f2 is None:
        self.right_gain_f2 = 0.
      if self.right_gain_f3 is None:
        self.right_gain_f3 = 0.
    else:
      self.left_bias_f1 = 0.
      self.left_bias_f2 = 0.
      self.left_bias_f3 = 0.
      self.left_gain_f1 = 0.
      self.left_gain_f2 = 0.
      self.left_gain_f3 = 0.
      self.right_bias_f1 = 0.
      self.right_bias_f2 = 0.
      self.right_bias_f3 = 0.
      self.right_gain_f1 = 0.
      self.right_gain_f2 = 0.
      self.right_gain_f3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_12d.pack(_x.left_bias_f1, _x.left_bias_f2, _x.left_bias_f3, _x.left_gain_f1, _x.left_gain_f2, _x.left_gain_f3, _x.right_bias_f1, _x.right_bias_f2, _x.right_bias_f3, _x.right_gain_f1, _x.right_gain_f2, _x.right_gain_f3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.left_bias_f1, _x.left_bias_f2, _x.left_bias_f3, _x.left_gain_f1, _x.left_gain_f2, _x.left_gain_f3, _x.right_bias_f1, _x.right_bias_f2, _x.right_bias_f3, _x.right_gain_f1, _x.right_gain_f2, _x.right_gain_f3,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_12d.pack(_x.left_bias_f1, _x.left_bias_f2, _x.left_bias_f3, _x.left_gain_f1, _x.left_gain_f2, _x.left_gain_f3, _x.right_bias_f1, _x.right_bias_f2, _x.right_bias_f3, _x.right_gain_f1, _x.right_gain_f2, _x.right_gain_f3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.left_bias_f1, _x.left_bias_f2, _x.left_bias_f3, _x.left_gain_f1, _x.left_gain_f2, _x.left_gain_f3, _x.right_bias_f1, _x.right_bias_f2, _x.right_bias_f3, _x.right_gain_f1, _x.right_gain_f2, _x.right_gain_f3,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_12d = struct.Struct("<12d")
class yaml_values(object):
  _type          = 'motor/yaml_values'
  _md5sum = 'b0738748015b35d4efcebe36d64e715c'
  _request_class  = yaml_valuesRequest
  _response_class = yaml_valuesResponse
